CLASS_INPUT =	./main/dominio/*.java \
				./main/domain/algoritmos/*.java \
				./main/domain/ed/*.java 

CLASS_OUTPUT =	../../EXE/out/



all:
	javac -d $(CLASS_OUTPUT) $(CLASS_INPUT)


clean:
	rm -r ../../EXE/out/*
